export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Jobs} from './Jobs'
export {default as JobsFreelancer} from './JobsFreelancer'
export {default as Freelancers} from './Freelancers'
export {default as DetailJob} from './DetailJob'
export {default as RegisterFreelancer} from './RegisterFreelancer'